"""
Regulus / json_builder.py
=========================
Assembles schema-compliant JSON from a ParsedDocument + ontology suggestions,
then validates against schema.json using jsonschema.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

SCHEMA_PATH = Path(__file__).parent.parent / "schema.json"

# ID sanitisation — must match schema pattern ^[a-zA-Z0-9._-]+$
import re
_ID_UNSAFE = re.compile(r'[^a-zA-Z0-9._-]')


def _safe_id(text: str) -> str:
    return _ID_UNSAFE.sub('-', text).strip('-') or "rule"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def load_schema(schema_path: str | Path = SCHEMA_PATH) -> dict:
    """Load schema.json and return as a dict."""
    path = Path(schema_path)
    if not path.exists():
        raise FileNotFoundError(f"schema.json not found at: {path}")
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def build_output(parsed_doc: Any, all_suggestions: list[list[Any]]) -> dict:
    """Assemble the output payload from a ParsedDocument and per-rule term suggestions.

    Parameters
    ----------
    parsed_doc : parser.ParsedDocument
    all_suggestions : list[list[TermSuggestion]]
        One inner list per rule, in the same order as parsed_doc.all_rules.
    """
    now = datetime.now(timezone.utc).isoformat()
    rules = parsed_doc.all_rules
    suggestions_map = {
        rule.rule_id: suggs
        for rule, suggs in zip(rules, all_suggestions)
    }

    output: dict[str, Any] = {
        "$schema": "https://crewrules.app/schemas/rule-ingestion/v1",
        "meta": {
            "schemaVersion": "1.0",
            "generatedAt": now,
            "generatedBy": "Regulus v0.1.0",
            "vendorSystem": "manual",
            "description": f"Ingested from {parsed_doc.source_file}",
        },
        "ruleset": _build_ruleset(parsed_doc),
        "rules": [
            _build_rule(rule, suggestions_map.get(rule.rule_id, []), parsed_doc.source_file)
            for rule in rules
        ],
        "ambiguityLog": _build_ambiguity_log(rules),
    }

    return output


def validate_output(output: dict, schema: dict) -> tuple[bool, list[str]]:
    """Validate output dict against the JSON schema.

    Returns (True, []) on success, or (False, [error_messages]) on failure.
    """
    try:
        import jsonschema
        validator = jsonschema.Draft202012Validator(schema)
        errors = sorted(validator.iter_errors(output), key=lambda e: list(e.path))
        if errors:
            messages = [f"{list(e.path)}: {e.message}" for e in errors]
            return False, messages
        return True, []
    except ImportError:
        return True, ["[WARNING] jsonschema not installed — validation skipped"]


def write_output(output: dict, dest_path: str | Path) -> Path:
    """Write validated output JSON to dest_path."""
    dest = Path(dest_path)
    dest.parent.mkdir(parents=True, exist_ok=True)
    with dest.open("w", encoding="utf-8") as f:
        json.dump(output, f, indent=2, ensure_ascii=False)
    return dest.resolve()


def write_python_repr(output: dict, dest_path: str | Path) -> Path:
    """Write a Python source file containing each rule as a named dict literal.

    The generated file can be pasted directly into a test module. Each rule is
    assigned to a variable named ``rule_<id>`` (with non-identifier chars replaced
    by underscores). A ``RULES`` list at the bottom collects all of them.

    Parameters
    ----------
    output:
        Validated output dict (from build_output / write_output).
    dest_path:
        Destination ``.py`` file path.

    Returns
    -------
    Path
        Resolved path of the written file.
    """
    import pprint

    dest = Path(dest_path)
    dest.parent.mkdir(parents=True, exist_ok=True)

    rules: list[dict] = output.get("rules", [])
    ruleset: dict = output.get("ruleset", {})

    lines: list[str] = [
        '"""',
        f'Python representation of rules ingested from: {output.get("meta", {}).get("description", "")}',
        f'Generated by: {output.get("meta", {}).get("generatedBy", "Regulus")}',
        f'Schema version: {output.get("meta", {}).get("schemaVersion", "1.0")}',
        '"""',
        "",
        "# Ruleset metadata",
        f"RULESET = {pprint.pformat(ruleset, indent=4)}",
        "",
    ]

    var_names: list[str] = []
    id_unsafe = re.compile(r"[^a-zA-Z0-9]")

    for rule in rules:
        rule_id = rule.get("id", "unknown")
        var = "rule_" + id_unsafe.sub("_", rule_id)
        var_names.append(var)

        # Build a clean dict with only populated schema fields
        rule_dict: dict = {}
        for field in ("id", "title", "referenceCode", "type", "rawText",
                      "dsl", "scope", "params", "visibility", "provenance",
                      "quarantineMetadata", "assumedTerms", "testCases",
                      "changeNotes", "tags", "lifecycleStatus", "notes", "assumptions"):
            if field in rule and rule[field] is not None:
                val = rule[field]
                # Omit empty lists/dicts
                if isinstance(val, (list, dict)) and not val:
                    continue
                rule_dict[field] = val

        lines.append(f"# Rule {rule_id}: {rule.get('title', '')[:60]}")
        lines.append(f"{var} = {pprint.pformat(rule_dict, indent=4)}")
        lines.append("")

    lines.append(f"RULES = [{', '.join(var_names)}]")
    lines.append("")

    dest.write_text("\n".join(lines), encoding="utf-8")
    return dest.resolve()


# ---------------------------------------------------------------------------
# Internal builders
# ---------------------------------------------------------------------------

def _build_ruleset(parsed_doc: Any) -> dict:
    meta = parsed_doc.doc_metadata
    title = meta.get("title", "") or parsed_doc.source_file

    # Try to infer jurisdiction from filename/title
    jurisdiction = "UNKNOWN"
    for known in ["EASA", "FAA", "CASA", "CAA", "DGCA"]:
        if known.lower() in (parsed_doc.source_file + title).lower():
            jurisdiction = known
            break

    return {
        "id": _safe_id(parsed_doc.source_file.replace(".pdf", "")),
        "name": title or parsed_doc.source_file,
        "jurisdiction": jurisdiction,
    }


def _build_rule(rule: Any, suggestions: list[Any], source_file: str) -> dict:
    now = datetime.now(timezone.utc).isoformat()
    meta = rule.metadata

    dsl = _build_dsl(rule, meta)
    provenance = _build_provenance(rule, source_file, now)
    assumed_terms = _build_assumed_terms(suggestions)

    rule_obj: dict[str, Any] = {
        "id": _safe_id(rule.rule_id),
        "title": rule.title[:200],
        "rawText": rule.raw_text,
        "dsl": dsl,
        "provenance": provenance,
    }

    if rule.references:
        rule_obj["notes"] = [f"References: {', '.join(rule.references)}"]

    if assumed_terms:
        rule_obj["assumedTerms"] = assumed_terms

    if rule.flags:
        rule_obj["tags"] = rule.flags
        rule_obj["quarantineMetadata"] = _build_quarantine(rule, now)
        rule_obj["lifecycleStatus"] = "quarantine"
    else:
        rule_obj["lifecycleStatus"] = "draft"

    return rule_obj


def _build_dsl(rule: Any, meta: dict) -> dict:
    dsl: dict[str, Any] = {"ruleType": meta.get("rule_type", "duty-limit")}

    limit_value = meta.get("limit_value")
    limit_unit = meta.get("limit_unit")
    condition_type = meta.get("condition_type")

    if limit_value is not None and condition_type:
        dsl["condition"] = {
            "type": condition_type,
            "field": _field_for_rule_type(dsl["ruleType"]),
            "value": limit_value,
            "unit": limit_unit or "hours",
        }

    rolling = meta.get("rolling_window")
    if rolling:
        dsl["rollingWindow"] = {
            "duration": rolling["duration"],
            "unit": rolling["unit"],
            "alignment": rolling.get("alignment", "homeBase"),
        }

    return dsl


def _field_for_rule_type(rule_type: str) -> str:
    return {
        "duty-limit": "dutyHours",
        "rest-period": "restHours",
        "flight-time-limit": "flightTimeHours",
        "day-off": "daysOff",
        "standby": "standbyHours",
        "cumulative-limit": "cumulativeHours",
        "positioning": "positioningHours",
        "augmented-crew": "augmentedFdpHours",
    }.get(rule_type, "dutyHours")


def _build_provenance(rule: Any, source_file: str, now: str) -> dict:
    return {
        "sourceFile": source_file,
        "extractedBy": "rules-ingestion-agent v0.1.0",
        "extractedAt": now,
        "pageReference": f"p.{rule.page_number}",
        "confidence": "medium" if not rule.flags else "low",
    }


def _build_assumed_terms(suggestions: list[Any]) -> list[dict]:
    terms = []
    for s in suggestions:
        t = s.term
        confidence = "high" if s.confidence >= 0.8 else ("medium" if s.confidence >= 0.5 else "low")
        terms.append({
            "code": t.code,
            "name": t.name,
            "category": t.category,
            "dataType": t.dataType,
            "unit": t.unit,
            "description": t.description,
            "aliases": t.aliases,
            "confidence": confidence,
        })
    return terms


def _build_quarantine(rule: Any, now: str) -> dict:
    ambiguities = []
    for flag in rule.flags:
        if flag == "VAGUE_LANGUAGE":
            ambiguities.append({
                "field": "rawText",
                "issue": "Rule contains vague language (e.g. 'reasonable', 'appropriate'). Numeric threshold unclear.",
                "suggestion": "Identify the specific numeric value or condition intended.",
            })
        elif flag == "NO_NUMERIC_LIMIT":
            ambiguities.append({
                "field": "dsl.condition.value",
                "issue": "No numeric limit detected in rule text. DSL condition value is unknown.",
                "suggestion": "Verify whether a numeric threshold applies and populate dsl.condition.value.",
            })

    checklist = [
        "Verify extracted rawText matches source document",
        "Confirm dsl.ruleType is correctly classified",
        "Resolve flagged ambiguities before promotion",
    ]

    return {
        "stagedAt": now,
        "reviewerChecklist": checklist,
        "ambiguities": ambiguities,
        "priority": "high" if ambiguities else "medium",
    }


def _build_ambiguity_log(rules: list[Any]) -> list[dict]:
    log = []
    for rule in rules:
        for i, flag in enumerate(rule.flags):
            log.append({
                "id": f"{rule.rule_id}-flag-{i}",
                "summary": f"Rule {rule.rule_id}: {flag}",
                "ruleId": rule.rule_id,
                "flag": flag,
            })
    return log
